# Generated by Django 5.2.6 on 2025-09-19 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text="A brief professional headline (e.g., 'Software Developer with 5 years experience')", max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True, help_text='A brief summary of your professional background and career goals')),
                ('skills', models.TextField(blank=True, help_text="List your key skills separated by commas (e.g., 'Python, Django, React, SQL')")),
                ('linkedin_url', models.URLField(blank=True, help_text='Your LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, help_text='Your GitHub profile URL')),
                ('portfolio_url', models.URLField(blank=True, help_text='Your portfolio or personal website URL')),
                ('other_url', models.URLField(blank=True, help_text='Any other relevant professional URL')),
                ('is_public', models.BooleanField(default=True, help_text='Make profile visible to recruiters')),
                ('is_seeking_jobs', models.BooleanField(default=True, help_text='Currently looking for job opportunities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant Profile',
                'verbose_name_plural': 'Applicant Profiles',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='Name of school or university', max_length=200)),
                ('degree', models.CharField(help_text="Degree type (e.g., Bachelor's, Master's)", max_length=100)),
                ('field_of_study', models.CharField(help_text='Field of study (e.g., Computer Science)', max_length=100)),
                ('start_date', models.DateField(help_text='Start date of education')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if currently studying)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Currently studying here')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='GPA (optional)', max_digits=3, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about your education')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (higher numbers first)')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='applicants.applicantprofile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education Records',
                'ordering': ['-order', '-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('position', models.CharField(help_text='Job title or position', max_length=200)),
                ('start_date', models.DateField(help_text='Start date of employment')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if currently working)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Currently working here')),
                ('location', models.CharField(blank=True, help_text='Work location', max_length=100)),
                ('description', models.TextField(help_text='Describe your responsibilities and achievements')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (higher numbers first)')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='applicants.applicantprofile')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experience Records',
                'ordering': ['-order', '-end_date', '-start_date'],
            },
        ),
    ]
