# Generated by Django 5.2.6 on 2025-09-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='country',
            field=models.CharField(blank=True, help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate (auto-populated if possible)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate (auto-populated if possible)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP Code', max_length=20),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='remote_work_preference',
            field=models.CharField(choices=[('remote_only', 'Remote Only'), ('hybrid', 'Hybrid'), ('onsite_only', 'Onsite Only'), ('flexible', 'Flexible')], default='flexible', help_text='Remote work preference', max_length=20),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='state',
            field=models.CharField(blank=True, help_text='State or Province', max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='willing_to_relocate',
            field=models.BooleanField(default=False, help_text='Willing to relocate for work'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Full location display (auto-generated)', max_length=200),
        ),
    ]
