# Generated by Django 5.0 on 2025-09-24 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "requirements",
                    models.TextField(help_text="Job requirements and qualifications"),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("temporary", "Temporary"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "remote_type",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("onsite", "On-site"),
                        ],
                        default="onsite",
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level (0-2 years)"),
                            ("mid", "Mid Level (3-5 years)"),
                            ("senior", "Senior Level (6+ years)"),
                            ("executive", "Executive Level"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="USD", max_length=3)),
                (
                    "salary_period",
                    models.CharField(
                        choices=[
                            ("hourly", "Per Hour"),
                            ("monthly", "Per Month"),
                            ("yearly", "Per Year"),
                        ],
                        default="yearly",
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="United States", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "required_skills",
                    models.TextField(
                        blank=True, help_text="Required skills, separated by commas"
                    ),
                ),
                (
                    "preferred_skills",
                    models.TextField(
                        blank=True, help_text="Preferred skills, separated by commas"
                    ),
                ),
                (
                    "visa_sponsorship",
                    models.BooleanField(
                        default=False, help_text="Visa sponsorship available"
                    ),
                ),
                (
                    "benefits",
                    models.TextField(blank=True, help_text="Benefits and perks"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        blank=True, help_text="Optional cover letter or note"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("review", "Under Review"),
                            ("interview", "Interview"),
                            ("offer", "Offer Extended"),
                            ("accepted", "Offer Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "unique_together": {("job", "applicant")},
            },
        ),
    ]
