# Generated by Django 5.2.6 on 2025-11-21 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='full_address',
            field=models.TextField(blank=True, help_text='Full address for geocoding and display'),
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map display', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map display', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='moderation_reason',
            field=models.TextField(blank=True, help_text='Optional reason provided by moderator when rejecting'),
        ),
        migrations.AddField(
            model_name='job',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Moderation status for admin review', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='kanban_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('review', 'Review'), ('interview', 'Interview'), ('offer', 'Offer'), ('closed', 'Closed')], default='applied', help_text='Status for kanban board management', max_length=20),
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Overall match score (0-100)')),
                ('skills_match_score', models.FloatField(help_text='Skills match score (0-100)')),
                ('location_match_score', models.FloatField(help_text='Location match score (0-100)')),
                ('experience_match_score', models.FloatField(help_text='Experience level match score (0-100)')),
                ('matched_skills', models.TextField(blank=True, help_text='Skills that matched, separated by commas')),
                ('missing_skills', models.TextField(blank=True, help_text='Required skills the applicant does not have')),
                ('recommendation_reason', models.TextField(blank=True, help_text='Explanation for why this job was recommended')),
                ('is_viewed', models.BooleanField(default=False, help_text='Whether the applicant has viewed this recommendation')),
                ('is_applied', models.BooleanField(default=False, help_text='Whether the applicant applied to this job')),
                ('is_dismissed', models.BooleanField(default=False, help_text='Whether the applicant dismissed this recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Recommendation',
                'verbose_name_plural': 'Job Recommendations',
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('applicant', 'job')},
            },
        ),
    ]
