# Generated by Django 5.2.6 on 2025-11-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('applicant', "I'm looking for a job"), ('recruiter', "I'm looking to hire"), ('admin', 'Administrator')], default='applicant', max_length=20),
        ),
    ]
