# Generated by Django 5.0 on 2025-09-24 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruiterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Company or organization name", max_length=200
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("startup", "Startup (1-10 employees)"),
                            ("small", "Small (11-50 employees)"),
                            ("medium", "Medium (51-200 employees)"),
                            ("large", "Large (201-1000 employees)"),
                            ("enterprise", "Enterprise (1000+ employees)"),
                        ],
                        default="medium",
                        help_text="Company size",
                        max_length=20,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, help_text="Industry or sector", max_length=100
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True, help_text="Company website")),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "company_description",
                    models.TextField(
                        blank=True, help_text="Brief description of your company"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruiter_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruiter Profile",
                "verbose_name_plural": "Recruiter Profiles",
            },
        ),
    ]
