# Generated by Django 5.2.6 on 2025-11-21 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this saved search', max_length=200)),
                ('keywords', models.CharField(blank=True, help_text='Search keywords', max_length=200)),
                ('skills', models.CharField(blank=True, help_text='Required skills', max_length=500)),
                ('location', models.CharField(blank=True, help_text='Location preference', max_length=200)),
                ('remote_preference', models.CharField(blank=True, choices=[('', 'Any'), ('remote_only', 'Remote Only'), ('hybrid', 'Hybrid'), ('onsite_only', 'Onsite Only'), ('flexible', 'Flexible')], help_text='Remote work preference', max_length=20)),
                ('experience_years', models.CharField(blank=True, choices=[('', 'Any'), ('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6-10', '6-10 years'), ('10+', '10+ years')], help_text='Experience level', max_length=10)),
                ('education_level', models.CharField(blank=True, choices=[('', 'Any'), ('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD')], help_text='Education level', max_length=20)),
                ('willing_to_relocate', models.BooleanField(default=False, help_text='Must be willing to relocate')),
                ('is_seeking_jobs', models.BooleanField(default=True, help_text='Must be actively seeking jobs')),
                ('notification_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='weekly', help_text='How often to receive notifications about new matches', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this search is active')),
                ('last_notified', models.DateTimeField(blank=True, help_text='Last time notifications were sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'ordering': ['-created_at'],
            },
        ),
    ]
